FROM python:3.11-alpine

RUN apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    curl \
    && pip install --no-cache-dir ansible

WORKDIR /project

CMD ["tail", "-f", "/dev/null"]